lib/grimoire_web/router.ex
defmodule GrimoireWeb.Router do
  use GrimoireWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GrimoireWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GrimoireWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/auth", GrimoireWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    delete "/logout", AuthController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", GrimoireWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: GrimoireWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/grimoire_web/templates/page/index.html.heex
<section class="phx-hero">
  <h1>Grimoire</h1>
  <%= if @current_user do %>
    <h2>Welcome, <%= @current_user.name %>!</h2>
    <div>
      <img src={ @current_user.avatar_url } />
    </div>
    <%= link "Logout", to: Routes.auth_path(@conn, :delete), method: "delete", class: "button" %>
    <br>
  <% else %>
    <ul style="list-style: none">
      <li>
        <a class="button" href={ Routes.auth_path(@conn, :request, "google") }>
        <i class="fa fa-google"></i>
        Sign in with Google
        </a>
      </li>
    </ul>
  <% end %>
</section>